version: "3.3"
services:
    web:
        image: mgromov/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/home/vagrant/nutterbg-bgapp/bgapp-mgromov/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: mgromov/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
networks:
    app-network:
