version: "3.3"
services:
    web:
        image: nutterbg/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        networks:
            - app-network
    db:
        image: nutterbg/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
networks:
    app-network:
